{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "firefly.fullname" . }}-postgres
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgresql.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    {{- include "firefly.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
